version: '3'

services:
  ourmenu-server:
    container_name: ourmenu-server
    restart: on-failure
    build:
      context: ../..
      dockerfile: infra/docker/Dockerfile
    ports:
      - "8080:8080"
    environment:
      TZ: Asia/Seoul
      KAKAO_API_KEY: ${KAKAO_API_KEY}
      MONGO_URL: ${MONGO_URL}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_BUCKET: ${S3_BUCKET}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      SPRING_SWAGGER_SERVER_URL: ${URL}
      DEFAULT_BUCKET_URL: ${DEFAULT_BUCKET_URL}
    volumes:
      - /var/log/springboot/:/var/log/springboot/
      - /etc/localtime:/etc/localtime:ro
